symbols:
  - code: JM2601
    start: 2025-09-03
  - code: M2601
    start: 2025-09-03
freq: "60m"
analysis:
  window_strength: 20
  window_zone: 60
  bins_pct: 0.5
  beta: 0.7
  half_life: 10
  quantile: 0.8
out_dir: "./data"
timezone: "Asia/Shanghai"
