symbols:
  - code: AO2601
    start: 2025-08-12
  - code: OI2601
    start: 2025-09-02
  - code: SR2601
    start: 2025-08-20
  - code: SP2601
    start: 2025-08-14
  - code: M2601
    start: 2025-08-13
  - code: SA2601
    start: 2025-09-15
  - code: UR2601
    start: 2025-08-19
  - code: V2601
    start: 2025-09-15

freq: "60m"
analysis:
  window_strength: 5
  window_zone: 60
  bins_pct: 0.5
  beta: 0.7
  half_life: 1000000000
  quantile: 0.8
out_dir: "./data"
timezone: "Asia/Shanghai"
