name: Update Futures Dashboard (Batch)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas matplotlib notion-client openpyxl

      - name: Run Batch Analysis
        env:
          SYMBOLS: JM2601,M2601,RB2601
        run: |
          python asi_chipzones_batch_v4.0_EN.py

      - name: Commit Updated Results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto update analysis results (batch)"
            git push
          fi

      - name: Push to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB: ${{ secrets.NOTION_DB }}
          NOTION_PARENT_PAGE: ${{ secrets.NOTION_PARENT_PAGE }}
        run: |
          python push_to_notion_v2.5_sync_and_dirfix.py
